name: CI

on:
  push:
    branches: ["**"]
  release:
    types: [published]

jobs:
  build:
    name: Build (${{ matrix.goos }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.modcache
          key: ${{ runner.os }}-go-${{ matrix.goos }}-${{ matrix.goarch }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: |
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            GOOS=windows GOARCH=${{ matrix.goarch }} go build -v -o dist/ones-cfg2md_windows_${{ matrix.goarch }}.exe ./...
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o dist/ones-cfg2md_linux_${{ matrix.goarch }} ./...
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ones-cfg2md-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: |
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            GOOS=windows GOARCH=${{ matrix.goarch }} go build -v -o dist/ones-cfg2md_windows_amd64.exe ./...
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o dist/ones-cfg2md_linux_amd64 ./...
          fi
      - name: Publish release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
